### ISSUE TITLE
Request: ConcurrentMultiThreadFlow required

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#23]
A version of MultiThreadFlow with concurrent queue is required. 

I made another repo, x2clr.match, on my github. 

To add database query, I need one. 

Thanks in advance.

**Comment by jaykang920** [comment]
Thanks for your feedback.

After initiating framework multi-targeting in v0.8.4,
I'm thinking of re-structuring Flow-Queue relationship in order to support ConcurrentQueue as default in .NET 4 and make it easy to apply custom behavior queues.
Since .NET allows the same name for generic and non-generic class, there will be no problem when we use `MultiThreadFlow` and `MultiThreadFlow<MyCustomQueue>`.

**Comment by keedongpark** [comment]
Awesome!
