### ISSUE TITLE
Q. What is a good way for a Case to suicide?

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#24]
Dynamic creation and destruction of Case appear quite often. 
- Game instances need to be created and destroyed dynamically
- User case need to be created and destroyed dynamically. 
- A game instance need to suicide when there is no member remained or game finished. 

Thanks in advance.

**Comment by keedongpark** [comment]
There might be a need to have a Flow internal event to support safe suicide of Case.

**Comment by keedongpark** [comment]
Adding a Flow function can also do, but it is usually safer to delay to next frame.

**Comment by jaykang920** [comment]
Thanks for your feedback.

Please consider a `Case` as a abstract partition of application logic rather than a simple event sink. `Case`-derived classes represent logically non-dividable units of an application.

Although you can dynamically add or remove cases, it is not natural to add/remove cases so frequently during an application execution.

For example, instead of making each game instance a separate case, you can introduce one `GameCase` that manages a list of internal game instances inheriting directly from `EventSink`.

And if you need one, you can write your own event to help killing your event sink in the next handler call.

**Comment by keedongpark** [comment]
To be a better framework, x2clr needs to reflect other views keeping core concepts. 

I think it will not harm to allow a view that: 
- Flow is a processing units of app. 
- Case is a logical units of app. like actor. 

While writing an instance based game, I cannot see any need to have one more level of Case to handle instance EventSink. 

Can you *please* provide an event to dynamically remove Case? 

Thank you ton.

**Comment by keedongpark** [comment]
Application level event which clears Case itself can be added
since Case.Dispose() is safe in event handler code. 

I will see how it goes.
