### ISSUE TITLE
x2.Fingerprint::GetLength()

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#8]
It seems that GetLength() returns more bytes than actual bytes since: 
- LengthInBytes() already counts all bytes. 
- Serializer.GetLengthVariable(uint value) returns 1 for length < 128 

I do not understand why GetLengthVariable() is added to LengthInBytes(). 

GetLength() function name needs to be changed if its intention is different.

**Comment by jaykang920** [comment]
Thanks for your feedback.

In x2clr, `GetLength()` method (defined in Cell, Event and Fingerprint) returns the number of bytes required to serialize the content of the current object.
It's similar with computeLength or something like that in Google Protocol Buffer.
`GetLength()` method is used when it is required to know the total number of bytes ahead before actually serializing an event, like in UDP links.
For cells and events, `GetLength()` method is built as a virtual method chain.
For fingerprint, it is simply the sum of the following two parts:

* `Serializer.GetLengthVariableNonnegative(length)` returns the number of bytes required to encode the number of bit flags (length member field)
* `LengthInBytes` property returns the number of bytes required to represent all the bit flags in this fingerprint.

`Fingerprint.GetLength()` consists of two parts because it is serialized in those two parts.
Please see the x2 binary format specification:
https://github.com/jaykang920/x2/blob/master/specs/binary-format.md#encoding-user-defined-types
