### ISSUE TITLE
class private field naming convention

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#9]
ReSharper shows that private field needs to have a underscore prefix. 
- https://www.jetbrains.com/help/resharper/2016.2/InconsistentNaming.html
- this.private field is not used consistently. 

I suggest following the MS guide to have underscore prefix for private class member field.

**Comment by jaykang920** [comment]
Thanks for your feedback.

MS guidelines do not specify naming private fields. It's just a ReSharper default.
we have our own coding style guide for x2clr:
https://github.com/jaykang920/x2clr/wiki/Coding-Style-Guide
Please note that underscores('_') are not allowed at any purpose, except a couple of very restricted uses.
I suggest you to tune your ReSharper settings to allow it.

You know coding style stuffs tend to being religious issues.
Since the dark age of Hungarian notation to struggle with under-developed tools, the obvious trend is to reduce non-semantic parts of the code.
At least in C# and Java, I don't think we need private member prefix or suffix, because recent cool IDEs are smart enough to visualize them.
In fact, I believe that using `this.` explicitly is even better. It keeps yourself more sensitive when using the same name for a local variable and a member field. 
Just try abandon underscores. It doesn't harm.
